packages:
  - "apps/*"
  - "packages/*"
catalog:
  typescript: ^5.8.3
  "@eslint/js": ^9.29.0
  eslint: 9.29.0
  tsup: ^8.4.0
  tsx: 4.19.3
  "@types/node": ^22.15.29
  graphql: ^16.11.0
  zod: ^3.24.2
  "@prisma/client": ^6.8.2
  "prisma": ^6.8.2
  tailwindcss: ^4.1.10
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.5
